language: generic

#from https://github.com/roswell/roswell/wiki/Travis-CI

addons:
  homebrew:
    update: true
    packages:
    - roswell
  apt:
    packages:
      - libc6-i386
      - default-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  jobs:
    - LISP=sbcl-bin DOCS=true
      COVERALLS_TEST=:noncoveralls-tests
    # CL-coveralls is temporaraly broken
    # - LISP=sbcl-bin COVERALLS=true COVERAGE_EXCLUDE=t:test-launcher.txt
    #   COVERALLS_TEST=:coveralls-tests  COVERALLS_REPO_TOKEN=ignore
    - LISP=abcl
      COVERALLS_TEST=:noncoveralls-tests
    - LISP=ecl
      COVERALLS_TEST=:noncoveralls-tests
    - LISP=alisp
      COVERALLS_TEST=:noncoveralls-tests
    - LISP=ccl-bin
      COVERALLS_TEST=:noncoveralls-tests
    - LISP=cmucl
      COVERALLS_TEST=:noncoveralls-tests

jobs:
  include:
    - os: osx
      env: LISP=sbcl-bin
      osx_image: xcode12.2
    - os: osx
      env: LISP=ccl-bin
      osx_image: xcode12.2

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install neil-lindquist/doc-site-generator

script:
  - roswell/run-fiveam.ros -l ci-utils/test :travis-tests $COVERALLS_TEST :base-tests


before_deploy:
  - copy-site-base docs docs-bin
  - echo "The documentation page for the CI-Utils Common Lisp library." | make-gh-page README.md docs-bin/index.md
  - ./generate-API-docs.ros

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs-bin
  on:
    branch: master
    condition: $DOCS = true
