name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: windows specific settings
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          echo "ROSWELL_INSTALL_DIR=$HOME/ros" >> $GITHUB_ENV
          echo "$HOME/ros/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v1
      - name: Install Roswell
        shell: bash
        env:
          LISP: ${{ matrix.lisp }}
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/v20.06.14.1077/scripts/install-for-ci.sh | sh -x
      - name: Run tests
        shell: bash
        run: roswell/run-fiveam.ros -l ci-utils/test :github-actions-tests :noncoveralls-tests :base-tests
